language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build
  - dotnet test tests/BluePhyre.Infrastructure.Tests/BluePhyre.Infrastructure.Tests.csproj
  - dotnet test tests/BluePhyre.Web.Tests/BluePhyre.Web.Tests.csproj
